### ISSUE TITLE
After some trial and error I find myself having progress pasted some errors, only to get taken by the prompts not proceeding past the initial propmt

### ISSUE THREAD

**Issue by ryanbishop12** [Holmeswww/AgentKit#11]
I installed this and made some mistakes understanding the instructions, couldn't get Environment Variable in right or set up the key file, I had it in the wrong location, its been a bit since I've at the command-line, so I interpreted the location of ~/.openai/openai.key to be within the workspace the I wrote the program in. After I realized my error and fixed that, installed the openai and anthropic pip packages, no idea if those are needed, I think it would have reached my current error even if that were different. A couple things came up following that, I ended up structuring my openai.key file to be key-value pairs, with 'key', 'organization', and 'key' being the keys, because it made sense to me that it would be structured that way, I have no clue if this is right though, if it is this needs to be made explicit instead of just quotes around the key that is to be represented. After it would start but would no show anything after matched model, I turned verbosity to True, though it just seems to have gotten stopped at the first prompt, never receiving a response or preforming another action. I tried with both claude-3 and gpt-3.5-turbo, neither completed. After letting it sit to see if anything would change, I began to try the my hand at the prompt-without-coding example. It worked to add the node, and enter the prompt, as well as potentially working on the features I did not test, as I wanted to see it in action, so I went ahead to select evaluate graph, after that is just stay on the path it was on but produced no subsequent actions. I would really like to be able to use this software as it seems to be such a promising development, bridging where modern AI users set their sights on in their mind, when being faced with the current abilities of AI, and the potential landscapes that could open up with widespread adoption of such a framework, one that enables simple commands be taken to enable creation of new products bypassing the normal R&D cycles businesses go through to develop new products. So I want your team to know that I am rooting for you to make this functional and able to bring it to production in a way that's scalable so more enthusiasts, developers, and business leaders can access this framework to help build their companies, and projects.

**Comment by Holmeswww** [comment]
Hi!

This seems to be related to https://github.com/Holmeswww/AgentKit/discussions/7

Currently, the LLM_API is made such that it catches all errors and retries the inputs. Let me push an update to expose errors in the LLM_API.

**Comment by Holmeswww** [comment]
b29b52f should address the issue.

Please upgrade to the latest release and set `verbose=True` for each node to see which node you are stuck on, and `LLM_API_FUNCTION.debug=True` to see what error is causing the error.
