### ISSUE TITLE
would this work okay with a local model on gpt4all?

### ISSUE THREAD

**Issue by nyck33** [Holmeswww/AgentKit#12]
if I rewrite parts of it to make calls to gpt4all running on local host with a small model like Mini Orca (small), do you think the results would be usable?  If I did that, would that be an acceptable contribution/pull request?

**Comment by Holmeswww** [comment]
Hi!

Thanks for offering to contribute. My impression for small models is that they're not yet ready for agentic flows. I wonder what you have observed playing with the small models.

**Comment by nyck33** [comment]
Can you provide some general guidelines on what you might try with smaller models?  I'm just starting with this now, have not even tried running with larger models because I"m afraid of the costs.  But are there ways to control the granularity of the subtasks for smaller models that might do better with smaller subtasks?

**Comment by Holmeswww** [comment]
Hi,
  I think it depends on what task you want to solve, and if the smaller model could execute your instructions accurately for the task.
