### ISSUE TITLE
AzureOpenAI Not Working

### ISSUE THREAD

**Issue by rhyswynn** [Holmeswww/AgentKit#15]
This line should be 
                    completion = client.chat.completions.create(

It is also not working when I fix this line, I am still troubleshooting, but the version I updated was working fine. Will you be making any changes to fix this, or should I just maintain my own version? Thank you

https://github.com/Holmeswww/AgentKit/blob/15000a976bbff8fc8e6480208ebaa5ec227afc6f/src/agentkit/llm_api/GPT.py#L92

**Comment by rhyswynn** [comment]
The other problem is because of the isInstance check, an AzureOpenAI client returns true for the isInstance check against OpenAI
![image](https://github.com/Holmeswww/AgentKit/assets/6010457/b6317360-d44c-4ac3-8a2f-0dac7cc33834)

**Comment by mattalford** [comment]
> This line should be completion = client.chat.completions.create(
> 
> It is also not working when I fix this line, I am still troubleshooting, but the version I updated was working fine. Will you be making any changes to fix this, or should I just maintain my own version? Thank you
> 
> https://github.com/Holmeswww/AgentKit/blob/15000a976bbff8fc8e6480208ebaa5ec227afc6f/src/agentkit/llm_api/GPT.py#L92

Thank you.  Yes, we should be using client.chat.completions.create and we don't need to check for Azure instance.  PR ready #16

**Comment by Holmeswww** [comment]
Merged
