### ISSUE TITLE
Could you please provide the code and scripts needed to reproduce the experiments?

### ISSUE THREAD

**Issue by ChaokunChang** [Holmeswww/AgentKit#26]
I really admire your work; it’s both interesting and promising. I would like to reproduce the experiments in the paper to gain a deeper understanding of AgentKit. Could you please provide the code and scripts needed to reproduce the experiments?

**Comment by Holmeswww** [comment]
a2a288ba91d65f6c95703bf6a9ecbecc5d32d402

Let me know if you encounter problems with it.
