### ISSUE TITLE
Installation Instructions are Insufficient 

### ISSUE THREAD

**Issue by 1of13** [Holmeswww/AgentKit#3]
The example usage script and installation instructions result in errors. There is no template for creating the "open.key" file nor instructions for where to put it. Additionally, some packages (e.g., openai, tiktoken) must be installed manually, as "pip install—e ." does not include them.

Your documentation leaves a lot to be desired as well.

**Comment by Holmeswww** [comment]
Hi, 

We kept the installation to minimal requirements, and therefore did not include OpenAI and tiktoken, since the idea is that the llm_api can be replaced by any user-provided functions.

However, it makes sense to update the documentation to reflect that.

**Comment by Holmeswww** [comment]
9ce67a314dd3f439f5cc0effc6e0199bc19f8f0e updates the documentation and usage of LLM_API
